### ISSUE TITLE
A sudden crush happens when launching godot.

### ISSUE THREAD

**Issue by hawahz** [godotengine/godot-builds#1]
I downloaded the godot engine at the beginning of August . It ran well that time . However, after a period of not using it, the crush happens. I tried to open with CMD, and nothing but the starting logs were displayed .
here is a video about how this happens:

https://github.com/godotengine/godot-builds/assets/145553087/f08c09f3-beb1-4958-a551-72070ae08210

I was using godot 4.1.1 when the crush happens. Then i turned to dev5 at my group friends' suggestion, and still no work. 
It specifically happens when i click any of the buttons ,except 'New Project'. I can create a new folder in the 'New Project' screen and enter the file explorer to select a folder, but otherwise (including click the SELECT button in the file explorer) everything i did causes the crush. But at the time i turn back to use Godot 3 , it runs normally .

Additionally, between the two runs in August and September, i have once updated the NVIDIA drivers .The system is Windows 11 all the time.

**Comment by YuriSizov** [comment]
Please open a bug report in the project's repository: https://github.com/godotengine/godot
