### ISSUE TITLE
AnimationSprite2d: Need to be able to set default, or persistent values

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot-builds#4]
Once you open a tilemap, and set the grid dimension, they REALLY should persist until set to something else. Having to remap the grid repeatedly for every sprite animation that uses the same tilemap is extremely cumbersome.

![Untitled](https://github.com/godotengine/godot-builds/assets/79280460/8d2c8ee4-8b2c-4629-ba21-7f15e3ac6aea)

**Comment by akien-mga** [comment]
This repository is to publish builds of Godot, not report bugs or submit proposals.

This looks like a proposal, so please file it in https://github.com/godotengine/godot-proposals
